// build_timestamp.h

/*
This file is generated by python
Options->Build Actions -> Pre-build command line
python "$PROJ_DIR$\build\pre_build.py" "$PROJ_DIR$\Inc\build_timestamp.h"
Local time: 2025-07-10 17:02:42
*/

#pragma once

const uint32_t RtcTask::BUILD_TIMESTAMP = 1752166962UL;
const uint32_t RtcTask::UTC_TIMESTAMP = 1752145362UL;
